from django.urls import path
from . import views

urlpatterns = [
    path('register-gym/', views.register_gym_form, name='register_gym_form'),
    path('registration-success/', views.gym_registration_success, name='gym_registration_success'),
    path('allocate-card/', views.allocate_card_to_gym_page, name='allocate_card_to_gym_page'),
    path('card-count/', views.gym_card_count, name='gym_card_count'),
    path('manage-cards/', views.manage_gym_cards, name='manage_gym_cards'),
    path('deallocate-nfc/', views.deallocate_gym_nfc, name='deallocate_gym_nfc'),
    path('manage-gyms/', views.manage_gyms, name='manage_gyms'),
    path('toggle-gym-approval/<str:gym_id>/', views.toggle_gym_approval, name='toggle_gym_approval'),
    path('update-subscription-dates/', views.update_gym_subscription_dates, name='update_gym_subscription_dates'),
    path('gym-dashboard/<str:gym_id>/', views.gym_dashboard, name='gym_dashboard'),
    path('create-subscription-plan/<str:gym_id>/', views.create_gym_subscription_plan, name='create_gym_subscription_plan'),
    path('subscribe/<str:gym_id>/<int:plan_id>/', views.subscribe_to_gym, name='subscribe_to_gym'),
    path('user-subscriptions/<str:gym_id>/', views.gym_user_subscriptions, name='gym_user_subscriptions'),
    path('manage-users/<str:gym_id>/', views.manage_gym_users, name='manage_gym_users'),
    path('nfc-add-user/<str:gym_id>/', views.nfc_add_gym_user_page, name='nfc_add_gym_user_page'),
    path('check_gym_nfc_allocation/', views.check_gym_nfc_allocation, name='check_gym_nfc_allocation'),
    path('allocate_gym_card/', views.allocate_gym_card, name='allocate_gym_card'),
    path('attendance/<str:gym_id>/', views.gym_attendance_page, name='gym_attendance_page'),
    path('all-attendance/<str:gym_id>/', views.gym_all_attendance, name='gym_all_attendance'),
    path('mark-attendance/<str:gym_id>/', views.mark_gym_attendance, name='mark_gym_attendance'),
    path('expenses/<str:gym_id>/', views.gym_expense_dashboard, name='gym_expense_dashboard'),
    path('add-expense/<str:gym_id>/', views.add_gym_expense, name='add_gym_expense'),
    path('edit-expense/<str:gym_id>/<int:expense_id>/', views.edit_gym_expense, name='edit_gym_expense'),
    path('delete-expense/<str:gym_id>/<int:expense_id>/', views.delete_gym_expense, name='delete_gym_expense'),
    path('balance-sheet/<str:gym_id>/', views.gym_balance_sheet, name='gym_balance_sheet'),
    path('browse/', views.browse_gyms, name='browse_gyms'),
    path('graph/<str:gym_id>/', views.gym_graph, name='gym_graph'),
    path('details/<str:gym_id>/', views.gym_details, name='gym_details'),
]
