# Generated by Django 5.2 on 2025-10-12 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_gym_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='name',
        ),
        migrations.AddField(
            model_name='gym',
            name='additional_services',
            field=models.TextField(blank=True, help_text='Any additional services offered', null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='business_type',
            field=models.CharField(default='Gym', max_length=50),
        ),
        migrations.AddField(
            model_name='gym',
            name='capacity',
            field=models.PositiveIntegerField(default=100, help_text='Maximum capacity of the venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='city',
            field=models.CharField(default='Default City', help_text='City of the venue location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='closing_time',
            field=models.TimeField(default='18:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='district',
            field=models.CharField(default='Default District', help_text='District of the venue location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='equipment_available',
            field=models.TextField(blank=True, help_text='List of available equipment', null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approval status of the application'),
        ),
        migrations.AddField(
            model_name='gym',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='max_banners',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of banners allowed'),
        ),
        migrations.AddField(
            model_name='gym',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='pincode',
            field=models.CharField(default='000000', help_text='Pincode of the venue location', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='social_media_links',
            field=models.TextField(blank=True, help_text='Comma separated list of social media links', null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='gyms_staffed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='state',
            field=models.CharField(default='Default State', help_text='State of the venue location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='thank_you_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='venue_location',
            field=models.TextField(default='Default location', help_text='Detailed location of the venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='venue_name',
            field=models.CharField(default='Default Venue', help_text='Name of the venue', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='joined_gyms', to=settings.AUTH_USER_MODEL),
        ),
    ]
