# Generated by Django 5.2 on 2025-10-12 07:38

import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_remove_gym_name_gym_additional_services_gym_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='id',
            field=models.CharField(default=gym.models.generate_gym_id, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
