# Generated by Django 5.2 on 2025-10-12 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_gym_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subscription plan', max_length=255)),
                ('start_date', models.DateField(help_text='The date when the subscription plan was created')),
                ('duration_in_months', models.IntegerField(help_text='Duration of the subscription plan in months')),
                ('duration_in_hours', models.IntegerField(default=0, help_text='Duration of the subscription plan in hours (if applicable)')),
                ('normal_price', models.DecimalField(decimal_places=2, help_text='The normal price of the subscription plan', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='The discounted price of the subscription plan (if any)', max_digits=10, null=True)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='gym.gym')),
                ('user', models.ForeignKey(help_text='The vendor who created this subscription plan', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym Subscription Plan',
                'verbose_name_plural': 'Gym Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='GymTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_transactions', to='gym.gymsubscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GymUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired')], default='valid', max_length=10)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gymsubscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym User Subscription',
                'verbose_name_plural': 'Gym User Subscriptions',
            },
        ),
    ]
