# Generated by Django 5.2 on 2025-10-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_gymattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='gym.gym')),
            ],
        ),
    ]
